# ===============================
# DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://sv-u6x9MYGV3yqrFNRCjPnb.cloud.elastika.pe:5432/tallermecanico
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

